{"timestamp":"2025-08-01T15:54:30.978421","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-01T15:54:30.978867","level":"info","event":"Filling up the DagBag from /home/user/airflow/dags/my_first_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-01T15:54:31.749344Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.749463Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.749529Z","level":"info","event":"Current task name:find_simulated_dates","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.749556Z","level":"info","event":"Dag name:ndvi_change_detection_pipeline_branching","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.757606Z","level":"info","event":"Using date_after_path: /home/user/airflow/historical_TIFs/2025-01-24_NDVI.tif","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.757727Z","level":"info","event":"Computed date_before_path: /home/user/airflow/historical_TIFs/2025-01-11_NDVI.tif","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.757601","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"TypeError","exc_value":"find_simulated_dates() got multiple values for argument 'ti'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/user/airflow/ndvi_utils.py","lineno":439,"name":"find_simulated_dates_wrapper"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-01T15:54:31.784452Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.784637Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.784711Z","level":"info","event":"Task:<Task(PythonOperator): find_simulated_dates>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:54:31.784754Z","level":"info","event":"Failure caused by find_simulated_dates() got multiple values for argument 'ti'","chan":"stdout","logger":"task"}
