{"timestamp":"2025-08-01T16:13:32.371157","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-01T16:13:32.371636","level":"info","event":"Filling up the DagBag from /home/user/airflow/dags/my_first_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-01T16:13:33.193594Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T16:13:33.193733Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T16:13:33.193808Z","level":"info","event":"Current task name:create_composite_before","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T16:13:33.193836Z","level":"info","event":"Dag name:ndvi_change_detection_pipeline_branching","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T16:13:33.201562","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"FileNotFoundError","exc_value":"[Errno 2] No such file or directory: '/home/user/airflow/mask.npy'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/user/airflow/dags/my_first_dag.py","lineno":142,"name":"create_composite_before_wrapper"},{"filename":"/home/user/airflow/ndvi_utils.py","lineno":693,"name":"create_composite_image"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/numpy/lib/_npyio_impl.py","lineno":454,"name":"load"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-01T16:13:33.217661Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T16:13:33.217859Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T16:13:33.217935Z","level":"info","event":"Task:<Task(PythonOperator): create_composite_before>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T16:13:33.217976Z","level":"info","event":"Failure caused by [Errno 2] No such file or directory: '/home/user/airflow/mask.npy'","chan":"stdout","logger":"task"}
