{"timestamp":"2025-08-01T15:00:20.816885","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-01T15:00:20.817315","level":"info","event":"Filling up the DagBag from /home/user/airflow/dags/my_first_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-01T15:00:20.208149Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:00:20.208281Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:00:20.208345Z","level":"info","event":"Current task name:branching_2","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:00:20.208371Z","level":"info","event":"Dag name:ndvi_change_detection_pipeline_branching","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:00:20.220379Z","level":"info","event":"Difference in days: 13 days, 0:00:00","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:00:20.236072","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"TypeError","exc_value":"'>' not supported between instances of 'datetime.timedelta' and 'int'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/branch.py","lineno":104,"name":"execute"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":258,"name":"choose_branch"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/user/airflow/ndvi_utils.py","lineno":270,"name":"decide_branch_2"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-01T15:00:20.257246Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:00:20.257401Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:00:20.257457Z","level":"info","event":"Task:<Task(BranchPythonOperator): branching_2>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T15:00:20.257484Z","level":"info","event":"Failure caused by '>' not supported between instances of 'datetime.timedelta' and 'int'","chan":"stdout","logger":"task"}
